language: ruby
rvm:
- 2.1.3
#services:
#- sqlite
#env:
#- DB=sqlite
before_script:
- bundle exec rake db:setup
#- rake db:setup
script:
- bin/rails db:migrate RAILS_ENV=test
- bundle exec rake test
#deploy:
#  on:
#    condition: "$DB = sqlite"
#  #provider: heroku
#  app: taskorganiser
#  run: "rake db:migrate"
