language: ruby
services:
- sqlite
env:
- DB=sqlite
before_script:
- rake db:setup
script:
#- bin/rails db:migrate RAILS_ENV=test
- rake test
deploy:
  on:
    condition: "$DB = sqlite"
  #provider: heroku
  app: taskorganiser
  run: "rake db:migrate"
